USE ROLE TELCO_ETL_ROLE;
USE WAREHOUSE COMPUTE_WH;
USE DATABASE TELCO_DB;
USE SCHEMA STAGING;

TRUNCATE TABLE STG_CUSTOMERS;

COPY INTO STG_CUSTOMERS
FROM @telco_pipeline_stage/customers/
FILE_FORMAT = (TYPE = PARQUET)
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;

TRUNCATE TABLE STG_ACTIVITY;

COPY INTO STG_ACTIVITY
FROM @telco_pipeline_stage/activity/
FILE_FORMAT = (TYPE = PARQUET)
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;

TRUNCATE TABLE STG_PLANS;

COPY INTO STG_PLANS
FROM @telco_pipeline_stage/plans/
FILE_FORMAT = (TYPE = PARQUET)
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;

select * from STG_ACTIVITY;

select * from STG_CUSTOMERS;

select * from STG_PLANS;