-- TELCO CUSTOMER 360 – SNOWFLAKE IAM SETUP 
-- Role: TELCO_ETL_ROLE
-- Purpose: Run end-to-end Telco ETL (S3 → STAGING → DW)

-- ========== 1. ROLE CREATION ==========
USE ROLE SECURITYADMIN;

CREATE ROLE IF NOT EXISTS TELCO_ETL_ROLE;

COMMENT ON ROLE TELCO_ETL_ROLE
IS 'Runs Telco Customer 360 ETL pipeline (Snowflake load & transform)';

-- Assign role to user
GRANT ROLE TELCO_ETL_ROLE TO USER OLUWATOSIN1998;

-- ========== 2. WAREHOUSE ACCESS ==========
USE ROLE ACCOUNTADMIN;

GRANT USAGE
ON WAREHOUSE COMPUTE_WH
TO ROLE TELCO_ETL_ROLE;

-- ========== 3. DATABASE ACCESS ==========
GRANT USAGE
ON DATABASE TELCO_DB
TO ROLE TELCO_ETL_ROLE;

-- ========== 4. SCHEMA ACCESS ==========

-- STAGING schema (raw → clean loads)
GRANT USAGE
ON SCHEMA TELCO_DB.STAGING
TO ROLE TELCO_ETL_ROLE;

GRANT CREATE TABLE
ON SCHEMA TELCO_DB.STAGING
TO ROLE TELCO_ETL_ROLE;

-- DW schema (transformed dimensional data)
GRANT USAGE
ON SCHEMA TELCO_DB.DW
TO ROLE TELCO_ETL_ROLE;

GRANT CREATE TABLE
ON SCHEMA TELCO_DB.DW
TO ROLE TELCO_ETL_ROLE;

GRANT CREATE PROCEDURE
ON SCHEMA TELCO_DB.DW
TO ROLE TELCO_ETL_ROLE;

-- ========== 5. TABLE PRIVILEGES ==========

-- STAGING tables (truncate & reload pattern)
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE
ON ALL TABLES IN SCHEMA TELCO_DB.STAGING
TO ROLE TELCO_ETL_ROLE;

GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE
ON FUTURE TABLES IN SCHEMA TELCO_DB.STAGING
TO ROLE TELCO_ETL_ROLE;

-- DW tables (transform & load)
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE
ON ALL TABLES IN SCHEMA TELCO_DB.DW
TO ROLE TELCO_ETL_ROLE;

GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE
ON FUTURE TABLES IN SCHEMA TELCO_DB.DW
TO ROLE TELCO_ETL_ROLE;

-- ========== 6. SPECIFIC TABLE OVERRIDES (OPTIONAL / EXPLICIT) ==========
-- Use only where tighter control or documentation clarity is needed

GRANT TRUNCATE, INSERT
ON TABLE TELCO_DB.DW.DIM_PLAN
TO ROLE TELCO_ETL_ROLE;

-- ========== 7. STAGE ACCESS (S3 → Snowflake) ==========
GRANT USAGE
ON STAGE TELCO_DB.STAGING.TELCO_PIPELINE_STAGE
TO ROLE TELCO_ETL_ROLE;

-- ========== 8. STORAGE INTEGRATION ACCESS ==========
GRANT USAGE
ON INTEGRATION TELCO_PIPELINE_INT
TO ROLE TELCO_ETL_ROLE;

-- ========== END OF IAM CONFIGURATION ==========
