-- ====== Procedure Scheduler =======
CREATE OR REPLACE TASK DW.CUSTOMER360_DAILY_TASK
WAREHOUSE = COMPUTE_WH
SCHEDULE = 'USING CRON 0 2 * * * UTC'
AS
CALL DW.SP_RUN_CUSTOMER360_PIPELINE();

-- ALTER TASK DW.CUSTOMER360_DAILY_TASK RESUME;

-- ALTER TASK DW.CUSTOMER360_DAILY_TASK SUSPEND;

-- ALTER TASK DW.CUSTOMER360_DAILY_TASK RESUME;


-- ====== Monitor Task Schedule =========
-- SELECT *
-- FROM TABLE(
--   INFORMATION_SCHEMA.TASK_HISTORY(
--     TASK_NAME => 'CUSTOMER360_DAILY_TASK',
--     RESULT_LIMIT => 10
--   )
-- )
-- ORDER BY SCHEDULED_TIME DESC;

-- EXECUTE TASK DW.CUSTOMER360_DAILY_TASK;