CREATE OR REPLACE PROCEDURE DW.SP_RUN_CUSTOMER360_PIPELINE()
RETURNS STRING
LANGUAGE SQL
AS
$$
BEGIN

    CALL STAGING.SP_LOAD_STAGING();
    CALL DW.SP_LOAD_DIM_PLAN();
    CALL DW.SP_LOAD_DIM_CUSTOMER();
    CALL DW.SP_LOAD_FACT_ACTIVITY();

    RETURN 'TELCO CUSTOMER360 PIPELINE COMPLETED SUCCESSFULLY';

END;
$$;

--CALL DW.SP_RUN_CUSTOMER360_PIPELINE();