USE ROLE TELCO_ETL_ROLE;
USE WAREHOUSE COMPUTE_WH;
USE DATABASE TELCO_DB;

CREATE OR REPLACE PROCEDURE TELCO_DB.STAGING.SP_LOAD_STAGING()
RETURNS STRING
LANGUAGE SQL
AS
$$
BEGIN
    -- Plans
    TRUNCATE TABLE TELCO_DB.STAGING.STG_PLANS;
    COPY INTO TELCO_DB.STAGING.STG_PLANS
    FROM @TELCO_DB.STAGING.TELCO_PIPELINE_STAGE/plans/
    FILE_FORMAT = (TYPE = PARQUET)
    MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;
    
    -- Customers
    TRUNCATE TABLE TELCO_DB.STAGING.STG_CUSTOMERS;
    COPY INTO TELCO_DB.STAGING.STG_CUSTOMERS
    FROM @TELCO_DB.STAGING.TELCO_PIPELINE_STAGE/customers/
    FILE_FORMAT = (TYPE = PARQUET)
    MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;
    
    -- Activity
    TRUNCATE TABLE TELCO_DB.STAGING.STG_ACTIVITY;
    COPY INTO TELCO_DB.STAGING.STG_ACTIVITY
    FROM @TELCO_DB.STAGING.TELCO_PIPELINE_STAGE/activity/
    FILE_FORMAT = (TYPE = PARQUET)
    MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;
    
    RETURN 'STAGING LOAD SUCCESS';
END;
$$;

-- CALL DW.SP_RUN_CUSTOMER360_PIPELINE();